// source: core/contract/account_contract.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    function () {
        return this;
    }.call(null) ||
    Function('return this')();

var core_Linda_pb = require('../../core/Linda_pb.cjs');
goog.object.extend(proto, core_Linda_pb);
goog.exportSymbol('LindaWebProto.AccountCreateContract', null, global);
goog.exportSymbol('LindaWebProto.AccountPermissionUpdateContract', null, global);
goog.exportSymbol('LindaWebProto.AccountUpdateContract', null, global);
goog.exportSymbol('LindaWebProto.SetAccountIdContract', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
LindaWebProto.AccountCreateContract = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(LindaWebProto.AccountCreateContract, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    LindaWebProto.AccountCreateContract.displayName = 'LindaWebProto.AccountCreateContract';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
LindaWebProto.AccountUpdateContract = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(LindaWebProto.AccountUpdateContract, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    LindaWebProto.AccountUpdateContract.displayName = 'LindaWebProto.AccountUpdateContract';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
LindaWebProto.SetAccountIdContract = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(LindaWebProto.SetAccountIdContract, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    LindaWebProto.SetAccountIdContract.displayName = 'LindaWebProto.SetAccountIdContract';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
LindaWebProto.AccountPermissionUpdateContract = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, LindaWebProto.AccountPermissionUpdateContract.repeatedFields_, null);
};
goog.inherits(LindaWebProto.AccountPermissionUpdateContract, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    LindaWebProto.AccountPermissionUpdateContract.displayName = 'LindaWebProto.AccountPermissionUpdateContract';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    LindaWebProto.AccountCreateContract.prototype.toObject = function (opt_includeInstance) {
        return LindaWebProto.AccountCreateContract.toObject(opt_includeInstance, this);
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!LindaWebProto.AccountCreateContract} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    LindaWebProto.AccountCreateContract.toObject = function (includeInstance, msg) {
        var f,
            obj = {
                ownerAddress: msg.getOwnerAddress_asB64(),
                accountAddress: msg.getAccountAddress_asB64(),
                type: jspb.Message.getFieldWithDefault(msg, 3, 0),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!LindaWebProto.AccountCreateContract}
 */
LindaWebProto.AccountCreateContract.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new LindaWebProto.AccountCreateContract();
    return LindaWebProto.AccountCreateContract.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!LindaWebProto.AccountCreateContract} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!LindaWebProto.AccountCreateContract}
 */
LindaWebProto.AccountCreateContract.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {!Uint8Array} */ (reader.readBytes());
                msg.setOwnerAddress(value);
                break;
            case 2:
                var value = /** @type {!Uint8Array} */ (reader.readBytes());
                msg.setAccountAddress(value);
                break;
            case 3:
                var value = /** @type {!LindaWebProto.AccountType} */ (reader.readEnum());
                msg.setType(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
LindaWebProto.AccountCreateContract.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    LindaWebProto.AccountCreateContract.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!LindaWebProto.AccountCreateContract} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
LindaWebProto.AccountCreateContract.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getOwnerAddress_asU8();
    if (f.length > 0) {
        writer.writeBytes(1, f);
    }
    f = message.getAccountAddress_asU8();
    if (f.length > 0) {
        writer.writeBytes(2, f);
    }
    f = message.getType();
    if (f !== 0.0) {
        writer.writeEnum(3, f);
    }
};

/**
 * optional bytes owner_address = 1;
 * @return {!(string|Uint8Array)}
 */
LindaWebProto.AccountCreateContract.prototype.getOwnerAddress = function () {
    return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * optional bytes owner_address = 1;
 * This is a type-conversion wrapper around `getOwnerAddress()`
 * @return {string}
 */
LindaWebProto.AccountCreateContract.prototype.getOwnerAddress_asB64 = function () {
    return /** @type {string} */ (jspb.Message.bytesAsB64(this.getOwnerAddress()));
};

/**
 * optional bytes owner_address = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOwnerAddress()`
 * @return {!Uint8Array}
 */
LindaWebProto.AccountCreateContract.prototype.getOwnerAddress_asU8 = function () {
    return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getOwnerAddress()));
};

/**
 * @param {!(string|Uint8Array)} value
 * @return {!LindaWebProto.AccountCreateContract} returns this
 */
LindaWebProto.AccountCreateContract.prototype.setOwnerAddress = function (value) {
    return jspb.Message.setProto3BytesField(this, 1, value);
};

/**
 * optional bytes account_address = 2;
 * @return {!(string|Uint8Array)}
 */
LindaWebProto.AccountCreateContract.prototype.getAccountAddress = function () {
    return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * optional bytes account_address = 2;
 * This is a type-conversion wrapper around `getAccountAddress()`
 * @return {string}
 */
LindaWebProto.AccountCreateContract.prototype.getAccountAddress_asB64 = function () {
    return /** @type {string} */ (jspb.Message.bytesAsB64(this.getAccountAddress()));
};

/**
 * optional bytes account_address = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAccountAddress()`
 * @return {!Uint8Array}
 */
LindaWebProto.AccountCreateContract.prototype.getAccountAddress_asU8 = function () {
    return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getAccountAddress()));
};

/**
 * @param {!(string|Uint8Array)} value
 * @return {!LindaWebProto.AccountCreateContract} returns this
 */
LindaWebProto.AccountCreateContract.prototype.setAccountAddress = function (value) {
    return jspb.Message.setProto3BytesField(this, 2, value);
};

/**
 * optional AccountType type = 3;
 * @return {!LindaWebProto.AccountType}
 */
LindaWebProto.AccountCreateContract.prototype.getType = function () {
    return /** @type {!LindaWebProto.AccountType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};

/**
 * @param {!LindaWebProto.AccountType} value
 * @return {!LindaWebProto.AccountCreateContract} returns this
 */
LindaWebProto.AccountCreateContract.prototype.setType = function (value) {
    return jspb.Message.setProto3EnumField(this, 3, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    LindaWebProto.AccountUpdateContract.prototype.toObject = function (opt_includeInstance) {
        return LindaWebProto.AccountUpdateContract.toObject(opt_includeInstance, this);
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!LindaWebProto.AccountUpdateContract} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    LindaWebProto.AccountUpdateContract.toObject = function (includeInstance, msg) {
        var f,
            obj = {
                accountName: msg.getAccountName_asB64(),
                ownerAddress: msg.getOwnerAddress_asB64(),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!LindaWebProto.AccountUpdateContract}
 */
LindaWebProto.AccountUpdateContract.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new LindaWebProto.AccountUpdateContract();
    return LindaWebProto.AccountUpdateContract.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!LindaWebProto.AccountUpdateContract} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!LindaWebProto.AccountUpdateContract}
 */
LindaWebProto.AccountUpdateContract.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {!Uint8Array} */ (reader.readBytes());
                msg.setAccountName(value);
                break;
            case 2:
                var value = /** @type {!Uint8Array} */ (reader.readBytes());
                msg.setOwnerAddress(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
LindaWebProto.AccountUpdateContract.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    LindaWebProto.AccountUpdateContract.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!LindaWebProto.AccountUpdateContract} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
LindaWebProto.AccountUpdateContract.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getAccountName_asU8();
    if (f.length > 0) {
        writer.writeBytes(1, f);
    }
    f = message.getOwnerAddress_asU8();
    if (f.length > 0) {
        writer.writeBytes(2, f);
    }
};

/**
 * optional bytes account_name = 1;
 * @return {!(string|Uint8Array)}
 */
LindaWebProto.AccountUpdateContract.prototype.getAccountName = function () {
    return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * optional bytes account_name = 1;
 * This is a type-conversion wrapper around `getAccountName()`
 * @return {string}
 */
LindaWebProto.AccountUpdateContract.prototype.getAccountName_asB64 = function () {
    return /** @type {string} */ (jspb.Message.bytesAsB64(this.getAccountName()));
};

/**
 * optional bytes account_name = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAccountName()`
 * @return {!Uint8Array}
 */
LindaWebProto.AccountUpdateContract.prototype.getAccountName_asU8 = function () {
    return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getAccountName()));
};

/**
 * @param {!(string|Uint8Array)} value
 * @return {!LindaWebProto.AccountUpdateContract} returns this
 */
LindaWebProto.AccountUpdateContract.prototype.setAccountName = function (value) {
    return jspb.Message.setProto3BytesField(this, 1, value);
};

/**
 * optional bytes owner_address = 2;
 * @return {!(string|Uint8Array)}
 */
LindaWebProto.AccountUpdateContract.prototype.getOwnerAddress = function () {
    return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * optional bytes owner_address = 2;
 * This is a type-conversion wrapper around `getOwnerAddress()`
 * @return {string}
 */
LindaWebProto.AccountUpdateContract.prototype.getOwnerAddress_asB64 = function () {
    return /** @type {string} */ (jspb.Message.bytesAsB64(this.getOwnerAddress()));
};

/**
 * optional bytes owner_address = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOwnerAddress()`
 * @return {!Uint8Array}
 */
LindaWebProto.AccountUpdateContract.prototype.getOwnerAddress_asU8 = function () {
    return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getOwnerAddress()));
};

/**
 * @param {!(string|Uint8Array)} value
 * @return {!LindaWebProto.AccountUpdateContract} returns this
 */
LindaWebProto.AccountUpdateContract.prototype.setOwnerAddress = function (value) {
    return jspb.Message.setProto3BytesField(this, 2, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    LindaWebProto.SetAccountIdContract.prototype.toObject = function (opt_includeInstance) {
        return LindaWebProto.SetAccountIdContract.toObject(opt_includeInstance, this);
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!LindaWebProto.SetAccountIdContract} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    LindaWebProto.SetAccountIdContract.toObject = function (includeInstance, msg) {
        var f,
            obj = {
                accountId: msg.getAccountId_asB64(),
                ownerAddress: msg.getOwnerAddress_asB64(),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!LindaWebProto.SetAccountIdContract}
 */
LindaWebProto.SetAccountIdContract.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new LindaWebProto.SetAccountIdContract();
    return LindaWebProto.SetAccountIdContract.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!LindaWebProto.SetAccountIdContract} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!LindaWebProto.SetAccountIdContract}
 */
LindaWebProto.SetAccountIdContract.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {!Uint8Array} */ (reader.readBytes());
                msg.setAccountId(value);
                break;
            case 2:
                var value = /** @type {!Uint8Array} */ (reader.readBytes());
                msg.setOwnerAddress(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
LindaWebProto.SetAccountIdContract.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    LindaWebProto.SetAccountIdContract.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!LindaWebProto.SetAccountIdContract} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
LindaWebProto.SetAccountIdContract.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getAccountId_asU8();
    if (f.length > 0) {
        writer.writeBytes(1, f);
    }
    f = message.getOwnerAddress_asU8();
    if (f.length > 0) {
        writer.writeBytes(2, f);
    }
};

/**
 * optional bytes account_id = 1;
 * @return {!(string|Uint8Array)}
 */
LindaWebProto.SetAccountIdContract.prototype.getAccountId = function () {
    return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * optional bytes account_id = 1;
 * This is a type-conversion wrapper around `getAccountId()`
 * @return {string}
 */
LindaWebProto.SetAccountIdContract.prototype.getAccountId_asB64 = function () {
    return /** @type {string} */ (jspb.Message.bytesAsB64(this.getAccountId()));
};

/**
 * optional bytes account_id = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAccountId()`
 * @return {!Uint8Array}
 */
LindaWebProto.SetAccountIdContract.prototype.getAccountId_asU8 = function () {
    return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getAccountId()));
};

/**
 * @param {!(string|Uint8Array)} value
 * @return {!LindaWebProto.SetAccountIdContract} returns this
 */
LindaWebProto.SetAccountIdContract.prototype.setAccountId = function (value) {
    return jspb.Message.setProto3BytesField(this, 1, value);
};

/**
 * optional bytes owner_address = 2;
 * @return {!(string|Uint8Array)}
 */
LindaWebProto.SetAccountIdContract.prototype.getOwnerAddress = function () {
    return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * optional bytes owner_address = 2;
 * This is a type-conversion wrapper around `getOwnerAddress()`
 * @return {string}
 */
LindaWebProto.SetAccountIdContract.prototype.getOwnerAddress_asB64 = function () {
    return /** @type {string} */ (jspb.Message.bytesAsB64(this.getOwnerAddress()));
};

/**
 * optional bytes owner_address = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOwnerAddress()`
 * @return {!Uint8Array}
 */
LindaWebProto.SetAccountIdContract.prototype.getOwnerAddress_asU8 = function () {
    return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getOwnerAddress()));
};

/**
 * @param {!(string|Uint8Array)} value
 * @return {!LindaWebProto.SetAccountIdContract} returns this
 */
LindaWebProto.SetAccountIdContract.prototype.setOwnerAddress = function (value) {
    return jspb.Message.setProto3BytesField(this, 2, value);
};

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
LindaWebProto.AccountPermissionUpdateContract.repeatedFields_ = [4];

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    LindaWebProto.AccountPermissionUpdateContract.prototype.toObject = function (opt_includeInstance) {
        return LindaWebProto.AccountPermissionUpdateContract.toObject(opt_includeInstance, this);
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!LindaWebProto.AccountPermissionUpdateContract} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    LindaWebProto.AccountPermissionUpdateContract.toObject = function (includeInstance, msg) {
        var f,
            obj = {
                ownerAddress: msg.getOwnerAddress_asB64(),
                owner: (f = msg.getOwner()) && core_Linda_pb.Permission.toObject(includeInstance, f),
                witness: (f = msg.getWitness()) && core_Linda_pb.Permission.toObject(includeInstance, f),
                activesList: jspb.Message.toObjectList(msg.getActivesList(), core_Linda_pb.Permission.toObject, includeInstance),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!LindaWebProto.AccountPermissionUpdateContract}
 */
LindaWebProto.AccountPermissionUpdateContract.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new LindaWebProto.AccountPermissionUpdateContract();
    return LindaWebProto.AccountPermissionUpdateContract.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!LindaWebProto.AccountPermissionUpdateContract} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!LindaWebProto.AccountPermissionUpdateContract}
 */
LindaWebProto.AccountPermissionUpdateContract.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {!Uint8Array} */ (reader.readBytes());
                msg.setOwnerAddress(value);
                break;
            case 2:
                var value = new core_Linda_pb.Permission();
                reader.readMessage(value, core_Linda_pb.Permission.deserializeBinaryFromReader);
                msg.setOwner(value);
                break;
            case 3:
                var value = new core_Linda_pb.Permission();
                reader.readMessage(value, core_Linda_pb.Permission.deserializeBinaryFromReader);
                msg.setWitness(value);
                break;
            case 4:
                var value = new core_Linda_pb.Permission();
                reader.readMessage(value, core_Linda_pb.Permission.deserializeBinaryFromReader);
                msg.addActives(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    LindaWebProto.AccountPermissionUpdateContract.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!LindaWebProto.AccountPermissionUpdateContract} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
LindaWebProto.AccountPermissionUpdateContract.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getOwnerAddress_asU8();
    if (f.length > 0) {
        writer.writeBytes(1, f);
    }
    f = message.getOwner();
    if (f != null) {
        writer.writeMessage(2, f, core_Linda_pb.Permission.serializeBinaryToWriter);
    }
    f = message.getWitness();
    if (f != null) {
        writer.writeMessage(3, f, core_Linda_pb.Permission.serializeBinaryToWriter);
    }
    f = message.getActivesList();
    if (f.length > 0) {
        writer.writeRepeatedMessage(4, f, core_Linda_pb.Permission.serializeBinaryToWriter);
    }
};

/**
 * optional bytes owner_address = 1;
 * @return {!(string|Uint8Array)}
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.getOwnerAddress = function () {
    return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * optional bytes owner_address = 1;
 * This is a type-conversion wrapper around `getOwnerAddress()`
 * @return {string}
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.getOwnerAddress_asB64 = function () {
    return /** @type {string} */ (jspb.Message.bytesAsB64(this.getOwnerAddress()));
};

/**
 * optional bytes owner_address = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOwnerAddress()`
 * @return {!Uint8Array}
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.getOwnerAddress_asU8 = function () {
    return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getOwnerAddress()));
};

/**
 * @param {!(string|Uint8Array)} value
 * @return {!LindaWebProto.AccountPermissionUpdateContract} returns this
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.setOwnerAddress = function (value) {
    return jspb.Message.setProto3BytesField(this, 1, value);
};

/**
 * optional Permission owner = 2;
 * @return {?LindaWebProto.Permission}
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.getOwner = function () {
    return /** @type{?LindaWebProto.Permission} */ (jspb.Message.getWrapperField(this, core_Linda_pb.Permission, 2));
};

/**
 * @param {?LindaWebProto.Permission|undefined} value
 * @return {!LindaWebProto.AccountPermissionUpdateContract} returns this
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.setOwner = function (value) {
    return jspb.Message.setWrapperField(this, 2, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!LindaWebProto.AccountPermissionUpdateContract} returns this
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.clearOwner = function () {
    return this.setOwner(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.hasOwner = function () {
    return jspb.Message.getField(this, 2) != null;
};

/**
 * optional Permission witness = 3;
 * @return {?LindaWebProto.Permission}
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.getWitness = function () {
    return /** @type{?LindaWebProto.Permission} */ (jspb.Message.getWrapperField(this, core_Linda_pb.Permission, 3));
};

/**
 * @param {?LindaWebProto.Permission|undefined} value
 * @return {!LindaWebProto.AccountPermissionUpdateContract} returns this
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.setWitness = function (value) {
    return jspb.Message.setWrapperField(this, 3, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!LindaWebProto.AccountPermissionUpdateContract} returns this
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.clearWitness = function () {
    return this.setWitness(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.hasWitness = function () {
    return jspb.Message.getField(this, 3) != null;
};

/**
 * repeated Permission actives = 4;
 * @return {!Array<!LindaWebProto.Permission>}
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.getActivesList = function () {
    return /** @type{!Array<!LindaWebProto.Permission>} */ (
        jspb.Message.getRepeatedWrapperField(this, core_Linda_pb.Permission, 4)
    );
};

/**
 * @param {!Array<!LindaWebProto.Permission>} value
 * @return {!LindaWebProto.AccountPermissionUpdateContract} returns this
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.setActivesList = function (value) {
    return jspb.Message.setRepeatedWrapperField(this, 4, value);
};

/**
 * @param {!LindaWebProto.Permission=} opt_value
 * @param {number=} opt_index
 * @return {!LindaWebProto.Permission}
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.addActives = function (opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, LindaWebProto.Permission, opt_index);
};

/**
 * Clears the list making it empty but non-null.
 * @return {!LindaWebProto.AccountPermissionUpdateContract} returns this
 */
LindaWebProto.AccountPermissionUpdateContract.prototype.clearActivesList = function () {
    return this.setActivesList([]);
};

goog.object.extend(exports, LindaWebProto);
